api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()

router.register(r"posts", views.PostViewSet)
router.register(r"category", views.CategoryViewSet)
router.register(r"users", views.UserViewSet)

app_name = "api"

urlpatterns = [
    path("", include(router.urls)),
    path("weather/", views.WeatherView.as_view(), name="weather"),
]


urlpatterns += router.urls

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/defender/", include("defender.urls")),
    path("admin/", admin.site.urls, name="admin"),
    path("", include("blog.urls")),
    path("users/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/", include("api.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path


from . import views

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("posts/", views.PostsView.as_view(), name="posts"),
    path(
        "posts/category/<int:category_id>/", views.PostsView.as_view(), name="category"
    ),
    path("posts/tag/<int:tag_id>/", views.PostsView.as_view(), name="tag-posts"),
    path(
        "post/<slug:slug>/",
        login_required(views.DetailPostView.as_view()),
        name="detail",
    ),
    path(
        "post/add-comment/<slug:slug>/",
        login_required(views.DetailPostView.as_view()),
        name="comment",
    ),
    path(
        "post/delete_comment/<int:id>/",
        views.delete_comment,
        name="delete_comment",
    ),
    path(
        "posts/my-posts/", login_required(views.PostUserList.as_view()), name="my-posts"
    ),
    path("post/delete/<int:post_id>/", views.remove_post, name="remove_post"),
    path("post/update/<int:pk>/", views.UpdatePostView.as_view(), name="update"),
    path(
        "favorite_list/",
        login_required(views.FavoriteListView.as_view()),
        name="favorite_list",
    ),
    path("posts/adddelfav/<int:post_id>/", views.add_or_delete_post, name="favorite"),
    path(
        "posts/create/", login_required(views.CreatePostView.as_view()), name="create"
    ),
    path("search/", views.search_request, name="search"),
]

blog/models.py
from django.db.models.query import QuerySet
from .validators import max_len_validator
from django.db import models
from users.models import User
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=150)

    def __str__(self):
        return self.title


class Tag(models.Model):
    caption = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.caption


class PostManager(models.Manager):
    def published(self):
        return super().get_queryset().filter(published=True)


class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField(validators=[max_len_validator])
    image = models.ImageField(upload_to="post_images/", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    last_update = models.DateTimeField(editable=False)
    published = models.BooleanField(default=True)
    slug = models.SlugField(default="", blank=True, null=False)
    views = models.IntegerField(default=0)
    category = models.ForeignKey(
        to=Category, on_delete=models.CASCADE, related_name="posts"
    )
    author = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name="posts")
    tag = models.ManyToManyField(to=Tag, related_name="posts")

    objects = PostManager()

    def __str__(self):
        return f"Post from {self.author} about {self.title} ({self.created.date()})"

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})

    def in_list(self):
        post = FavoriteList.objects.filter(user=self.author, post=self)
        return post.exists()

    def len_text(self):
        return len(self.text) > 50

    class Meta:
        ordering = ["-created"]


class Comment(models.Model):
    text = models.CharField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(
        to=User, on_delete=models.CASCADE, related_name="comments"
    )

    def __str__(self) -> str:
        return f"Comment from {self.author.username}"


class FavoriteList(models.Model):
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms
from .models import Post, Comment, Tag


class PostForm(forms.ModelForm):
    tag = forms.ModelChoiceField(Tag.objects.all())

    class Meta:
        model = Post
        fields = ["title", "text", "image", "category", "tag"]


class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "text"]


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "Enter your comment here"})
    )

    class Meta:
        model = Comment
        fields = ["text"]
        labels = {"text": "Your comment"}


class SearchForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Post
        exclude = ["post", "author"]

blog/views.py
from datetime import datetime


from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from weather.apiweather import get_weather


from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.core.exceptions import PermissionDenied
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from common.views import TitleMixin

from .forms import CommentForm, PostForm, SearchForm, UpdatePostForm
from .models import Category, Comment, FavoriteList, Post


class IndexView(TitleMixin, TemplateView):
    title = "My blog"
    template_name = "blog/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = Post.objects.filter(published=True).values(
            "slug", "title", "text"
        )[:3]
        context["time"] = datetime.now()
        context["weather"] = get_weather()
        return context


# List, Detail post
class PostsView(TitleMixin, ListView):
    title = "All posts"
    template_name = "blog/posts.html"
    queryset = Post.objects.all()
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        if self.kwargs.get("tag_id"):
            context["user_post"] = Post.objects.filter(
                author=self.request.user
            ).distinct()
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published=True)
        category_id = self.kwargs.get("category_id")
        tag = self.kwargs.get("tag_id")
        return (
            queryset.filter(Q(category_id=category_id) | Q(tag=tag))
            if category_id or tag
            else queryset
        )


class DetailPostView(TitleMixin, View):
    title = "Detail"

    def get(self, request, slug):
        post = Post.objects.get(slug=slug)
        form = CommentForm()
        session = request.session.get("key", [])

        if not session:
            session = request.session["key"] = []
        if post.slug not in session:
            session.append(post.slug)

        post.views += 1
        post.save()
        context = {
            "object": post,
            "title": "Detail",
            "comment_form": form,
            "comments": post.comments.all().order_by("-created_date"),
        }
        return render(request, "blog/post-detail.html", context=context)

    def post(self, request, slug):
        form = CommentForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data.get("text")
            post = Post.objects.get(slug=slug)
            Comment.objects.create(author=self.request.user, text=text, post=post)
            messages.success(request, "Good work!")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])


def delete_comment(request, id):
    comment = Comment.objects.filter(id=id, author=request.user)
    if comment.first():
        comment.delete()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


# Creating, Update, Delete
class CreatePostView(TitleMixin, CreateView):
    title = "Create post"
    model = Post
    template_name = "blog/create-post.html"
    form_class = PostForm
    success_url = reverse_lazy("blog:index")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreatePostView, self).form_valid(form)


class UpdatePostView(TitleMixin, UpdateView):
    title = "Update post"
    template_name = "blog/update.html"
    model = Post
    form_class = UpdatePostForm
    success_url = reverse_lazy("blog:my-posts")

    def get_object(self, queryset=None):
        post = get_object_or_404(Post, pk=self.kwargs["pk"])
        if str(post.author) != self.request.user.username:
            raise PermissionDenied("Доступ запрещен")

        return post

    def post(self, request, pk):
        post = self.get_object()
        form = UpdatePostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(request.META["HTTP_REFERER"])


def is_staff(user):
    return user.is_staff


@user_passes_test(is_staff)
def remove_post(request, post_id):
    post_to_remove = Post.objects.get(id=post_id)
    post_to_remove.delete()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


class PostUserList(TitleMixin, ListView):
    title = "Post list"
    template_name = "blog/list_user.html"
    model = Post

    def total_posts(self):
        all = Post.objects.filter(author=self.request.user)
        return len(all)

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(author=self.request.user)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["total_posts"] = self.total_posts()
        return context


def search_request(request):
    if request.method == "GET":
        form = SearchForm()
        return render(request, "blog/search.html", {"form": form})
    if request.method == "POST":
        result = request.POST.get("search_query")
        posts = Post.objects.filter(
            Q(text__icontains=result) | Q(title__icontains=result)
        )
        return render(request, "blog/search.html", {"posts": posts})


# Favorite list and add to this list
class FavoriteListView(ListView):
    model = FavoriteList
    template_name = "blog/favorite_list.html"

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        queryset.filter(user=user)
        return queryset.filter(user=user)


@login_required()
def add_or_delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user
    favlist = FavoriteList.objects.filter(user=user, post=post)
    if not favlist.exists():
        FavoriteList.objects.create(user=user, post=post)
        return HttpResponseRedirect(request.META["HTTP_REFERER"])
    else:
        favlist.delete()
        return HttpResponseRedirect(request.META["HTTP_REFERER"])

templates/blog/create-post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <title>Create your post</title>
</head>
<body>
    
<form action="{%url 'blog:create'%}" method="post" enctype='multipart/form-data'>
    
        {% csrf_token %}
        {% for object in form %}
        <div class='form-control {% if object.errors %} error {% endif %}'>
            {{object.label_tag}}
            {{object}}
            {{object.errors}}
        </div>    
        {% endfor %}
        <button type='submit'>Send</button>
 </form>

   
    

templates/blog/favorite_list.html
{% extends "base.html" %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{%static 'css/stored-posts.css'%}">{% endblock css %}



{% block content %}
<section id="stored-posts">
    <ul>
        {%for object in object_list%}
        <li>
            <a href="{%url 'blog:detail' object.post.slug%}">{{object.post.title}}</a>
        </li>
        {% endfor %}
        
    </ul>
</section>

{% endblock content %}

templates/blog/index.html
{%extends 'base.html'%}
{% load static cache%}

{%block title%}{{title}} {%endblock%}
{% block css %}
<link rel="stylesheet" href="{%static 'css/index.css'%}">
<link rel="stylesheet" href="{%static 'css/post.css'%}">
{% endblock css %}




{% block content %} 
<style>

#openweathermap-widget-18 {
    width: 300px;
    height: 200px;
    margin: 0 auto; 
    display: flex;
    justify-content: center; 
    align-items: center; 
}
</style>

<section id='welcome'>
    <header>
        
        <img src="#" alt="Serhii - The author of this blog">
        <h2>SERHII BLOG</h2>
    </header>
    <p>Hello everybody</p>

    
</section>

<section id='latest-posts'>
    <h2>My latest posts</h2>
    
    <ul>
        
        {%for object in object_list%}
        <li> 
           <article class='post'>
            <a href="{% url "blog:detail" object.slug %}">
                {% if user.is_authenticated and object.image %}
                    <img src="{{object.image.url}}" alt="Mountain Hiking" height=100, weight=100>
                {% else %}
                    <img src="{%static 'img/woods.jpg'%}" alt="Mountain Hiking" height=100, weight=10>
                {% endif %}
                
                <div class="post__content">
                    <h3>{{object.title}}</h3>
                    {% if object.len_text %}
                    <p>{{object.text|slice:':50'}}...</p>
                    {% else %}
                    <p>{{object.text}}</p>
                    {% endif %}
                    
                </div>
            </a>
           </article> 
</li>
{%endfor%}
</ul>

<p></p>
    

</section>

<section id='about'>
    <h2>What I do</h2>
    <p>This inform about me</p>
    <p>I love programming</p>
    <div id="openweathermap-widget-14"></div>
<div id="openweathermap-widget-18"></div>
<script>window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = [];  window.myWidgetParam.push({id: 18,cityid: '703448',appid: 'df67202e561aa89447225443fd7bfefa',units: 'metric',containerid: 'openweathermap-widget-18',  });  (function() {var script = document.createElement('script');script.async = true;script.charset = "utf-8";script.src = "//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js";var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(script, s);  })();</script>
    <a href="{% url "api:weather" %}">Want check your weather?</a>

</section>

{%endblock %}

templates/blog/list_user.html
{{title}}
{% block content %}
<ul>
    {% for object in object_list  %}
    <li>
        <a href="{{object.get_absolute_url}}">{{object.title}}</a>
        author is: {{object.author}}
        <a href="{%url 'blog:update' object.id%}"><button>Update</button></a>
        <a href="{%url 'blog:remove_post' object.id%}"><button>Delete</button></a>
        
    </li>
    {% endfor %}
</ul>
<p>In total: {{total_posts}}</p>
{% endblock content %}

templates/blog/post-detail.html
{% extends 'base.html' %}
{% load static humanize %}
{% block title %}{{title}}{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{%static 'css/post-detail.css'%}">
{% endblock css %}

{% block content %}

{% if messages %}
    {% for message in messages  %}
    {{message}}
    {% endfor %}
{% endif %}
<section id='summary'>
<h2>{{object.title}}</h2>

<div>
    {% for tag in object.tag.all %} 
    <span class='tag'><a href="{% url 'blog:tag-posts' tag.id%}">{{tag.caption}}</a></span> 
    {% endfor %}
</div>


<div id='read-later' class="mt-5">
    {% if not object.in_list %}
        <a href="{%url 'blog:favorite' object.id%}"><button>Read Later</button></a>
    {% else %}
        <a href="{%url 'blog:favorite' object.id%}"><button>Delete from list</button></a>
    {% endif %}
   
    
</div>
<article>
{%if object.image%}
<img src="{{object.image.url}}" alt="">
{% endif %}
<address><h4>Author: {{object.author|title}}</h4></address>
<div>
    <p>Last update: {{object.last_update|naturaltime}}</p>
</div>

</article>

</section>




<main>
    <p>
        {{object.text|linebreaks}}
    </p>
    
</main>

{% if comments %}
<section id="comments"> 
    <ul>

    <h4>Total comments: {{comments.count}}</h4>
        
    {% for comment in comments  %}
    <li><h2>{{comment.text}}</h2></li>
    <li><h4>{{comment.author}} {{comment.created_date}}</h4></li>
    <li><a href="{%url 'blog:delete_comment' comment.id%}"><button>Delete comment</button></a></li>
    {% endfor %}
    </ul>
{% else %}
    <h2 class='text-center'>No comments, be first!</h2>


</section>
{% endif %}

<div>
    <form id="comment-form" action={%url 'blog:detail' object.slug%} method="post">
        {% csrf_token %}
        {% for field in comment_form  %}
        <div class='form-control {% if field.errors %}invalid{% endif %}'>
           {{field.label_tag}}
            {{field}} 
            {{field.error}}
        </div> 
        {% endfor %} 
        <button type='submit'>Send comment</button>
    </form>
</div>


{% endblock content %}

templates/blog/posts.html
{% extends 'base.html' %}
{%load static cache%}

{%block title%}All my posts{%endblock%}
{% block css %}
<link rel="stylesheet" href="{%static 'css/all-posts.css'%}">
<link rel="stylesheet" href="{%static 'css/post.css'%}">
{% endblock css %}




{% block content %} 

<section id="all-posts">
    
<ul>
    {% for object in object_list  %}
    <li> 
        <article class='post'>
            <a href="{{object.get_absolute_url}}">
                {% if user.is_authenticated and object.image %}
                    <img src="{{object.image.url}}" alt="Mountain Hiking" height=100, weight=100>
                {% else %}
                    <img src="{%static 'img/woods.jpg'%}" alt="Mountain Hiking" height=100, weight=10>
                {% endif %}
                <div class="post__content">
                    <h3>{{object.title}}</h3>
                    {% if object.len_text %}
                    <p>{{object.text|slice:":50"}} ...</p>
                    {% else %}
                    <p>{{object.text}}</p>
                    {% endif %}
                    
                    
                    
                </div>
            </a>
            {%cache 60 if%}
            {% if user.is_authenticated %}
                {% if not object.in_list %}
                    <p><a href="{%url 'blog:favorite' object.id%}"><button>Add to favorite list</button></a></p>
                    {% else %}
                    <p><a href="{%url 'blog:favorite' object.id%}"><button>Delete from favorite list</button></a></p>
                {% endif %}
            {% if user.is_staff %}
                <p><a href="{%url 'blog:remove_post' object.id%}"><button>Delete this post!</button></a></p>
            {% endif %} 
            {% if object in user_post or user.is_staff %}
            <p><a href="{%url 'blog:update' object.id%}"><button>Update</button></a></p>
            {% endif %}   
                
            {% endif %}
            {%endcache%}
        </article> 
           
    </li>
    {% endfor %}
</ul> 
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

</section>

<div class="row text-center">

        <div class="col-lg-3">
            <div class="list-group">
                {%cache 120 categories%}
                {%for category in categories%}
                <a href="{%url 'blog:category' category.pk%}" class="list-group-item">{{category.title}}</a>
                {%endfor%}
                {%endcache%}
            </div>

        </div>


{% endblock %}

templates/blog/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{%url 'blog:search'%}" method="post">
    {% csrf_token %}
    <input type="text" name="search_query">
    <button type="submit">Search</button>
</form>

{% if posts %}
<ul>
   {% for post in posts %}
   <li>
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
   </li>
{% endfor %} 
</ul>

{% else %}
<p>Not result</p>
 {% endif %}
</body>
</html>

templates/blog/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    <form action="{%url 'blog:update' object.id%}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
    </form>
</body>
</html>