api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()

router.register(r"posts", views.PostViewSet)
router.register(r"category", views.CategoryViewSet)
router.register(r"users", views.UserViewSet)

app_name = "api"

urlpatterns = [
    path("", include(router.urls)),
    path("weather/", views.WeatherView.as_view(), name="weather"),
]


urlpatterns += router.urls

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/defender/", include("defender.urls")),
    path("admin/", admin.site.urls, name="admin"),
    path("", include("blog.urls")),
    path("users/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/", include("api.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path


from . import views

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("posts/", views.PostsView.as_view(), name="posts"),
    path(
        "posts/category/<int:category_id>/", views.PostsView.as_view(), name="category"
    ),
    path("posts/tag/<int:tag_id>/", views.PostsView.as_view(), name="tag-posts"),
    path(
        "post/<slug:slug>/",
        login_required(views.DetailPostView.as_view()),
        name="detail",
    ),
    path(
        "post/add-comment/<slug:slug>/",
        login_required(views.DetailPostView.as_view()),
        name="comment",
    ),
    path(
        "post/delete_comment/<int:id>/",
        views.delete_comment,
        name="delete_comment",
    ),
    path(
        "posts/my-posts/", login_required(views.PostUserList.as_view()), name="my-posts"
    ),
    path("post/delete/<int:post_id>/", views.remove_post, name="remove_post"),
    path("post/update/<int:pk>/", views.UpdatePostView.as_view(), name="update"),
    path(
        "favorite_list/",
        login_required(views.FavoriteListView.as_view()),
        name="favorite_list",
    ),
    path("posts/adddelfav/<int:post_id>/", views.add_or_delete_post, name="favorite"),
    path(
        "posts/create/", login_required(views.CreatePostView.as_view()), name="create"
    ),
    path("search/", views.search_request, name="search"),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "emailverif/<str:email>/<uuid:code>/",
        views.EmailverificationView.as_view(),
        name="verif",
    ),
    path("profile/<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path("block-time/", views.DefenderBlockView.as_view(), name="defender"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{%static 'css/app.css'%}">
    {% block css %}{% endblock css %}
</head>
<body> 
<header id="main-navigation">
    <h1><a href="{%url 'blog:index'%}">Serhii Blog</a></h1>
    <nav>
        <a href="{%url 'blog:posts'%}">All posts</a>
        <a href="{% url 'blog:search'%}">Search</a>
    </nav>
    <nav>
        {%if user.is_authenticated%}
            {% if user.is_verification %}
                <a href="{% url 'blog:create' %}">Create Post</a>
                <a href="{%url 'blog:my-posts'%}">My posts</a>
            {% endif %}
        <a href="{% url "users:profile" user.id%}">Profile</a>
        <a href="{%url 'blog:favorite_list'%}">Favorite List</a>
        <a href="{%url 'users:logout'%}">Logout</a>
        {%else%}
        <a href="{%url 'users:login'%}">Login</a>
        {% endif %}
    </nav>
</header>
{% block content %}

   
{% endblock content %}
</body>
</html>